"""Realistic starter data for a fresh local garage installation."""

from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
from typing import Any


def seed_data() -> dict[str, list[dict[str, Any]]]:
    today = date.today()
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()

    def day(offset: int) -> str:
        return (today + timedelta(days=offset)).isoformat()

    def stamp(offset_days: int = 0, hour: int = 10) -> str:
        return datetime.combine(
            today + timedelta(days=offset_days),
            datetime.min.time().replace(hour=hour),
            tzinfo=timezone.utc,
        ).isoformat()

    customers = [
        {
            "id": "cus_001",
            "name": "Aarav Sharma",
            "phone": "+91 98765 43210",
            "email": "aarav.sharma@example.com",
            "address": "Indiranagar, Bengaluru",
            "notes": "Prefers WhatsApp updates.",
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "cus_002",
            "name": "Riya Kapoor",
            "phone": "+91 98220 11122",
            "email": "riya.kapoor@example.com",
            "address": "Koregaon Park, Pune",
            "notes": "Fleet account contact.",
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "cus_003",
            "name": "Vikram Mehta",
            "phone": "+91 98111 77889",
            "email": "vikram.mehta@example.com",
            "address": "Gurugram, Haryana",
            "notes": None,
            "created_at": now,
            "updated_at": now,
        },
    ]

    vehicles = [
        {
            "id": "veh_001",
            "customer_id": "cus_001",
            "make": "Honda",
            "model": "City ZX",
            "year": 2022,
            "registration_number": "KA01MX4821",
            "vin": "MAKGM4580N1234567",
            "color": "Pearl White",
            "fuel_type": "Petrol",
            "transmission": "CVT",
            "odometer": 28412,
            "status": "in_service",
            "image_url": None,
            "notes": "Use 0W-20 fully synthetic oil.",
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "veh_002",
            "customer_id": "cus_002",
            "make": "Hyundai",
            "model": "Creta SX(O)",
            "year": 2023,
            "registration_number": "MH12QH9014",
            "vin": "MALPB813PPM728204",
            "color": "Galaxy Blue",
            "fuel_type": "Diesel",
            "transmission": "Automatic",
            "odometer": 11250,
            "status": "checked_in",
            "image_url": None,
            "notes": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "veh_003",
            "customer_id": "cus_003",
            "make": "Tata",
            "model": "Nexon EV",
            "year": 2024,
            "registration_number": "HR26EV7689",
            "vin": "MAT628201RZ112233",
            "color": "Pristine White",
            "fuel_type": "Electric",
            "transmission": "Automatic",
            "odometer": 8640,
            "status": "ready",
            "image_url": None,
            "notes": "Do not wash charging port with high pressure.",
            "created_at": now,
            "updated_at": now,
        },
    ]

    jobs = [
        {
            "id": "job_001",
            "job_number": "WO-1001",
            "vehicle_id": "veh_001",
            "customer_id": "cus_001",
            "service_type": "Periodic maintenance",
            "description": "30,000 km service, oil and cabin filter replacement.",
            "status": "in_progress",
            "priority": "normal",
            "technician": "Rahul Verma",
            "scheduled_at": stamp(0, 9),
            "due_at": stamp(1, 17),
            "odometer": 28412,
            "estimated_cost": 6800.0,
            "labor_cost": 1200.0,
            "parts_cost": 4250.0,
            "notes": "Customer approved estimate by phone.",
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "job_002",
            "job_number": "WO-1002",
            "vehicle_id": "veh_002",
            "customer_id": "cus_002",
            "service_type": "Brake inspection",
            "description": "Inspect front brake noise and rotor wear.",
            "status": "scheduled",
            "priority": "high",
            "technician": "Neha Singh",
            "scheduled_at": stamp(0, 13),
            "due_at": stamp(0, 18),
            "odometer": 11250,
            "estimated_cost": 3500.0,
            "labor_cost": 0.0,
            "parts_cost": 0.0,
            "notes": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "job_003",
            "job_number": "WO-1003",
            "vehicle_id": "veh_003",
            "customer_id": "cus_003",
            "service_type": "Battery health check",
            "description": "Annual EV battery and charging system health check.",
            "status": "completed",
            "priority": "normal",
            "technician": "Ankit Rao",
            "scheduled_at": stamp(-2, 10),
            "due_at": stamp(-1, 16),
            "odometer": 8640,
            "estimated_cost": 1800.0,
            "labor_cost": 1200.0,
            "parts_cost": 0.0,
            "notes": "Battery health: 96%.",
            "created_at": now,
            "updated_at": now,
        },
    ]

    appointments = [
        {
            "id": "apt_001",
            "customer_id": "cus_001",
            "vehicle_id": "veh_001",
            "service_type": "Service check-in",
            "starts_at": stamp(0, 9),
            "ends_at": stamp(0, 9)[:-6] + "+00:00",
            "status": "checked_in",
            "advisor": "Ishita Bose",
            "notes": "Keys left at reception.",
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "apt_002",
            "customer_id": "cus_002",
            "vehicle_id": "veh_002",
            "service_type": "Brake inspection",
            "starts_at": stamp(0, 13),
            "ends_at": stamp(0, 14),
            "status": "confirmed",
            "advisor": "Ishita Bose",
            "notes": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "apt_003",
            "customer_id": "cus_003",
            "vehicle_id": "veh_003",
            "service_type": "EV annual inspection",
            "starts_at": stamp(2, 11),
            "ends_at": stamp(2, 12),
            "status": "confirmed",
            "advisor": "Sameer Khan",
            "notes": "Customer will wait in lounge.",
            "created_at": now,
            "updated_at": now,
        },
    ]

    inventory = [
        {
            "id": "part_001",
            "sku": "OIL-0W20-4L",
            "name": "0W-20 Fully Synthetic Engine Oil (4L)",
            "category": "Lubricants",
            "quantity_on_hand": 14,
            "reorder_level": 6,
            "unit_price": 2450.0,
            "supplier": "AutoCare Distributors",
            "location": "Aisle A-02",
            "notes": None,
            "stock_movements": [],
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "part_002",
            "sku": "FILTER-CAB-109",
            "name": "Cabin Air Filter - Honda City",
            "category": "Filters",
            "quantity_on_hand": 3,
            "reorder_level": 5,
            "unit_price": 780.0,
            "supplier": "Honda Parts Hub",
            "location": "Aisle B-05",
            "notes": "Reorder this week.",
            "stock_movements": [],
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "part_003",
            "sku": "BRAKE-PAD-HC-22",
            "name": "Front Brake Pad Set - Hyundai Creta",
            "category": "Brakes",
            "quantity_on_hand": 2,
            "reorder_level": 2,
            "unit_price": 3950.0,
            "supplier": "Mobility Components Ltd.",
            "location": "Aisle C-01",
            "notes": None,
            "stock_movements": [],
            "created_at": now,
            "updated_at": now,
        },
    ]

    invoices = [
        {
            "id": "inv_001",
            "invoice_number": "INV-2001",
            "customer_id": "cus_003",
            "vehicle_id": "veh_003",
            "job_id": "job_003",
            "line_items": [
                {
                    "description": "EV battery health check",
                    "quantity": 1,
                    "unit_price": 1200.0,
                    "inventory_id": None,
                    "total": 1200.0,
                }
            ],
            "status": "paid",
            "subtotal": 1200.0,
            "tax_rate": 18.0,
            "tax_amount": 216.0,
            "discount": 0.0,
            "total": 1416.0,
            "amount_paid": 1416.0,
            "balance_due": 0.0,
            "due_at": stamp(0, 17),
            "issued_at": stamp(-1, 16),
            "notes": "Paid by UPI.",
            "payments": [
                {
                    "id": "pay_001",
                    "amount": 1416.0,
                    "method": "upi",
                    "reference": "UPI-EXAMPLE-001",
                    "paid_at": stamp(-1, 16),
                }
            ],
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": "inv_002",
            "invoice_number": "INV-2002",
            "customer_id": "cus_001",
            "vehicle_id": "veh_001",
            "job_id": "job_001",
            "line_items": [
                {
                    "description": "Periodic maintenance estimate",
                    "quantity": 1,
                    "unit_price": 6800.0,
                    "inventory_id": None,
                    "total": 6800.0,
                }
            ],
            "status": "issued",
            "subtotal": 6800.0,
            "tax_rate": 18.0,
            "tax_amount": 1224.0,
            "discount": 0.0,
            "total": 8024.0,
            "amount_paid": 0.0,
            "balance_due": 8024.0,
            "due_at": stamp(7, 17),
            "issued_at": stamp(0, 10),
            "notes": "Estimate pending customer payment.",
            "payments": [],
            "created_at": now,
            "updated_at": now,
        },
    ]

    settings = [
        {
            "id": "settings",
            "garage_name": "Torque Garage",
            "phone": "+91 80 4000 4200",
            "email": "hello@torquegarage.example",
            "address": "100 Service Lane, Bengaluru, Karnataka",
            "timezone": "Asia/Kolkata",
            "currency": "INR",
            "tax_rate": 18.0,
            "opening_hours": "Mon–Sat, 8:30 AM–7:00 PM",
            "created_at": now,
            "updated_at": now,
        }
    ]

    return {
        "settings": settings,
        "customers": customers,
        "vehicles": vehicles,
        "jobs": jobs,
        "appointments": appointments,
        "inventory": inventory,
        "invoices": invoices,
    }
